2024-06-25 15:50:30,760 INFO    StreamThr :7233 [internal.py:wandb_internal():85] W&B internal server running at pid: 7233, started at: 2024-06-25 15:50:30.757288
2024-06-25 15:50:30,762 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status
2024-06-25 15:50:30,776 INFO    WriterThread:7233 [datastore.py:open_for_write():87] open: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155030-1/run-1.wandb
2024-06-25 15:50:30,777 DEBUG   SenderThread:7233 [sender.py:send():378] send: header
2024-06-25 15:50:30,811 DEBUG   SenderThread:7233 [sender.py:send():378] send: run
2024-06-25 15:50:31,403 INFO    SenderThread:7233 [dir_watcher.py:__init__():211] watching files in: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155030-1/files
2024-06-25 15:50:31,403 INFO    SenderThread:7233 [sender.py:_start_run_threads():1123] run started: 1 with start time 1719327030.755052
2024-06-25 15:50:35,834 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:50:36,418 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:50:40,862 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:50:41,438 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:50:45,890 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:50:46,454 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:50:50,915 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:50:51,476 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:50:55,942 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:50:56,308 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:50:56,309 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:50:56,309 ERROR   SenderThread:7233 [sender.py:send_run():970] run 1 was previously created and deleted; try a new run name (Error 409: Conflict)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2188, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 968, in send_run
    server_run = self._init_run(run, config_value_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 1013, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run 1 was previously created and deleted; try a new run name (Error 409: Conflict)
2024-06-25 15:50:56,316 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:50:56,500 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:01,340 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:01,520 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:06,359 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:06,536 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:11,384 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:11,548 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:16,402 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:16,566 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:21,424 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:21,579 INFO    StreamThr :7233 [internal.py:wandb_internal():85] W&B internal server running at pid: 7233, started at: 2024-06-25 15:51:21.555357
2024-06-25 15:51:21,587 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status
2024-06-25 15:51:21,590 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:21,596 INFO    WriterThread:7233 [datastore.py:open_for_write():87] open: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155121-1/run-1.wandb
2024-06-25 15:51:21,601 DEBUG   SenderThread:7233 [sender.py:send():378] send: header
2024-06-25 15:51:21,631 DEBUG   SenderThread:7233 [sender.py:send():378] send: run
2024-06-25 15:51:21,944 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:21,944 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:51:23,107 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:23,108 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:51:25,430 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:25,430 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:51:25,431 INFO    SenderThread:7233 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-06-25 15:51:26,442 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:26,603 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:26,662 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:51:30,563 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:30,564 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:51:31,459 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:31,618 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:36,480 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:36,639 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:39,861 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:39,861 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:51:41,495 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:41,656 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:46,512 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:46,674 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:51,531 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:51,694 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:56,551 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:56,713 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:51:59,992 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:51:59,992 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:52:01,561 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:01,734 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:06,575 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:06,751 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:11,589 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:11,772 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:16,606 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:16,790 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:21,626 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:21,807 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:26,644 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:26,828 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:31,666 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:31,846 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:36,687 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:36,868 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:38,841 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:52:38,841 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:52:41,708 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:41,888 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:46,728 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:46,911 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:51,746 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:51,935 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:56,771 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:52:56,960 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:01,792 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:01,978 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:06,807 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:06,991 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:11,830 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:12,006 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:16,849 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:17,018 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:21,864 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:22,036 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:26,883 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:27,050 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:31,894 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:32,070 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:36,907 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:37,087 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:41,927 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:42,099 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:46,944 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:47,121 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:51,955 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:52,135 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:52,292 ERROR   SenderThread:7233 [internal_api.py:execute():344] 409 response executing GraphQL.
2024-06-25 15:53:52,293 ERROR   SenderThread:7233 [internal_api.py:execute():345] {"errors":[{"message":"run 1 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-06-25 15:53:52,294 ERROR   SenderThread:7233 [sender.py:send_run():970] run 1 was previously created and deleted; try a new run name (Error 409: Conflict)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 2188, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 312, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 340, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 968, in send_run
    server_run = self._init_run(run, config_value_dict)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/sender.py", line 1013, in _init_run
    server_run, inserted, server_messages = self._api.upsert_run(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run 1 was previously created and deleted; try a new run name (Error 409: Conflict)
2024-06-25 15:53:52,301 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:56,973 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:57,159 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:53:57,322 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:01,989 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:02,176 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:02,343 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:07,004 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:07,189 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:07,358 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:12,022 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:12,205 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:12,373 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:17,047 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:17,222 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:17,391 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:22,060 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:22,244 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:22,408 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:27,081 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:27,257 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:27,428 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:32,096 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:32,271 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:32,444 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:37,112 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:37,293 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:37,461 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:42,127 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:42,311 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:42,479 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:47,149 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:47,333 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:47,493 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:52,172 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:52,347 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:52,515 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:57,187 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:57,371 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:54:57,536 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:02,205 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:02,390 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:02,552 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:07,223 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:07,402 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:07,568 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:12,249 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:12,424 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:12,586 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:17,270 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:17,436 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:17,608 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:22,288 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:22,453 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:22,629 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:27,312 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:27,473 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:27,641 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:32,328 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:32,498 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:32,665 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:37,343 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:37,509 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:37,680 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:42,365 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:42,529 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:42,691 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:47,380 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:47,546 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:47,705 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:51,450 INFO    StreamThr :7233 [internal.py:wandb_internal():85] W&B internal server running at pid: 7233, started at: 2024-06-25 15:55:51.436754
2024-06-25 15:55:51,465 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status
2024-06-25 15:55:51,487 INFO    WriterThread:7233 [datastore.py:open_for_write():87] open: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155551-pzrb463e/run-pzrb463e.wandb
2024-06-25 15:55:51,489 DEBUG   SenderThread:7233 [sender.py:send():378] send: header
2024-06-25 15:55:51,586 DEBUG   SenderThread:7233 [sender.py:send():378] send: run
2024-06-25 15:55:52,010 INFO    SenderThread:7233 [dir_watcher.py:__init__():211] watching files in: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155551-pzrb463e/files
2024-06-25 15:55:52,010 INFO    SenderThread:7233 [sender.py:_start_run_threads():1123] run started: pzrb463e with start time 1719327351.428361
2024-06-25 15:55:52,390 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:52,561 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:52,725 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:56,622 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:55:57,032 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:57,402 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:57,577 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:55:57,742 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:01,647 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:02,053 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:02,424 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:02,594 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:02,763 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:06,677 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:07,073 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:07,448 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:07,608 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:07,780 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:11,703 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:12,092 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:12,466 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:12,619 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:12,797 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:16,715 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:17,109 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:17,487 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:17,643 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:17,816 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:21,739 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:22,130 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:22,509 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:22,653 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:22,833 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:26,767 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:27,150 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:27,523 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:27,668 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:27,847 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:31,789 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:32,173 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:32,535 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:32,689 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:32,864 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:36,812 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:37,194 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:37,552 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:37,710 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:37,883 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:41,837 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:42,213 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:42,572 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:42,727 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:42,899 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:46,853 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:47,227 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:47,587 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:47,743 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:47,916 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:51,874 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:52,244 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:52,611 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:52,761 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:52,935 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:56,904 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:56:57,267 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:57,625 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:57,791 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:56:57,947 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:01,925 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:02,292 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:02,651 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:02,806 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:02,968 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:06,945 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:07,309 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:07,669 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:07,819 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:07,985 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:11,976 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:12,326 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:12,685 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:12,834 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:13,005 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:16,998 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:17,345 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:17,707 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:17,857 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:18,020 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:22,022 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: cancel
2024-06-25 15:57:22,023 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: cancel
2024-06-25 15:57:22,364 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:22,721 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:22,871 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:23,033 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:27,384 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:27,735 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:27,887 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:28,054 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:32,402 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:32,754 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:32,909 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:33,077 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:37,420 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:37,777 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:37,928 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:38,094 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:42,440 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:42,796 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:42,944 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:43,116 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:47,458 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:47,625 INFO    StreamThr :7233 [internal.py:wandb_internal():85] W&B internal server running at pid: 7233, started at: 2024-06-25 15:57:47.620545
2024-06-25 15:57:47,627 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status
2024-06-25 15:57:47,630 INFO    WriterThread:7233 [datastore.py:open_for_write():87] open: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155747-96zg6qi4/run-96zg6qi4.wandb
2024-06-25 15:57:47,631 DEBUG   SenderThread:7233 [sender.py:send():378] send: header
2024-06-25 15:57:47,685 DEBUG   SenderThread:7233 [sender.py:send():378] send: run
2024-06-25 15:57:47,817 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:47,968 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:48,098 INFO    SenderThread:7233 [dir_watcher.py:__init__():211] watching files in: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155747-96zg6qi4/files
2024-06-25 15:57:48,098 INFO    SenderThread:7233 [sender.py:_start_run_threads():1123] run started: 96zg6qi4 with start time 1719327467.612847
2024-06-25 15:57:48,123 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: check_version
2024-06-25 15:57:48,124 DEBUG   SenderThread:7233 [sender.py:send_request():405] send_request: check_version
2024-06-25 15:57:48,138 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:52,479 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:52,829 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:52,987 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:53,142 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:53,153 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:53,286 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:57,495 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:57,845 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:58,005 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:58,164 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:57:58,172 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:57:58,302 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:02,516 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:02,863 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:03,024 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:03,177 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:03,193 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:03,316 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:07,533 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:07,878 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:08,044 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:08,200 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:08,211 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:08,325 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:12,552 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:12,891 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:13,056 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:13,216 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:13,231 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:13,340 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:17,571 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:17,908 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:18,075 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:18,251 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:18,252 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: run_start
2024-06-25 15:58:18,271 DEBUG   HandlerThread:7233 [system_info.py:__init__():26] System info init
2024-06-25 15:58:18,271 DEBUG   HandlerThread:7233 [system_info.py:__init__():41] System info init done
2024-06-25 15:58:18,271 INFO    HandlerThread:7233 [system_monitor.py:start():194] Starting system monitor
2024-06-25 15:58:18,272 INFO    SystemMonitor:7233 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-06-25 15:58:18,272 INFO    HandlerThread:7233 [system_monitor.py:probe():214] Collecting system info
2024-06-25 15:58:18,273 INFO    SystemMonitor:7233 [interfaces.py:start():188] Started cpu monitoring
2024-06-25 15:58:18,273 INFO    SystemMonitor:7233 [interfaces.py:start():188] Started disk monitoring
2024-06-25 15:58:18,277 INFO    SystemMonitor:7233 [interfaces.py:start():188] Started gpuapple monitoring
2024-06-25 15:58:18,280 INFO    SystemMonitor:7233 [interfaces.py:start():188] Started memory monitoring
2024-06-25 15:58:18,281 INFO    SystemMonitor:7233 [interfaces.py:start():188] Started network monitoring
2024-06-25 15:58:18,520 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:18,586 ERROR   HandlerThread:7233 [gpu_apple.py:probe():176] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:18,586 DEBUG   HandlerThread:7233 [system_info.py:probe():150] Probing system
2024-06-25 15:58:18,588 DEBUG   HandlerThread:7233 [system_info.py:_probe_git():135] Probing git
2024-06-25 15:58:18,608 DEBUG   HandlerThread:7233 [system_info.py:_probe_git():143] Probing git done
2024-06-25 15:58:18,609 DEBUG   HandlerThread:7233 [system_info.py:probe():198] Probing system done
2024-06-25 15:58:18,609 DEBUG   HandlerThread:7233 [system_monitor.py:probe():223] {'os': 'macOS-13.3-arm64-arm-64bit', 'python': '3.11.4', 'heartbeatAt': '2024-06-25T14:58:18.586885', 'startedAt': '2024-06-25T14:57:47.600895', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/rajit906/Symmetry-invariant-Tractable-Generative-Models.git', 'commit': '1b52995cd6402c49af310d5b374cd97eb6c08306'}, 'email': None, 'root': '/Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models', 'host': 'Rajits-MacBook-Air.local', 'username': 'rajit906', 'executable': '/usr/local/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 11.354015350341797}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-06-25 15:58:18,609 INFO    HandlerThread:7233 [system_monitor.py:probe():224] Finished collecting system info
2024-06-25 15:58:18,609 INFO    HandlerThread:7233 [system_monitor.py:probe():227] Publishing system info
2024-06-25 15:58:18,609 INFO    HandlerThread:7233 [system_monitor.py:probe():229] Finished publishing system info
2024-06-25 15:58:18,619 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:18,620 DEBUG   SenderThread:7233 [sender.py:send():378] send: files
2024-06-25 15:58:18,620 INFO    SenderThread:7233 [sender.py:_save_file():1389] saving file wandb-metadata.json with policy now
2024-06-25 15:58:19,247 INFO    Thread-46 :7233 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155747-96zg6qi4/files/wandb-metadata.json
2024-06-25 15:58:19,362 INFO    wandb-upload_0:7233 [upload_job.py:push():130] Uploaded file /var/folders/sx/y6c6vjtn04719m5bcb52hk3r0000gn/T/tmpbh5xrbijwandb/f5gz03ku-wandb-metadata.json
2024-06-25 15:58:20,627 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:22,591 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:22,735 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:22,922 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:23,090 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:23,264 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:23,272 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:23,643 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:24,846 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:26,955 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:27,604 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:27,943 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:28,104 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:28,278 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:28,297 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:28,654 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:29,066 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:31,181 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:32,627 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:32,965 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:33,123 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:33,292 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:33,294 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:33,315 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:33,667 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:35,407 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:37,539 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:37,646 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:37,981 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:38,140 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:38,315 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:38,336 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:38,684 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:39,645 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:41,771 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:42,671 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:43,000 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:43,160 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:43,336 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:43,356 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:43,703 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:43,911 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:46,047 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:47,682 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:48,024 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:48,180 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:48,184 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:48,370 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:48,527 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: python_packages
2024-06-25 15:58:48,527 DEBUG   SenderThread:7233 [sender.py:send_request():405] send_request: python_packages
2024-06-25 15:58:48,527 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: stop_status
2024-06-25 15:58:48,528 DEBUG   SenderThread:7233 [sender.py:send_request():405] send_request: stop_status
2024-06-25 15:58:48,739 DEBUG   SenderThread:7233 [sender.py:send():378] send: telemetry
2024-06-25 15:58:48,740 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:49,378 INFO    Thread-46 :7233 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155747-96zg6qi4/files/requirements.txt
2024-06-25 15:58:50,501 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:52,710 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:52,726 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:53,039 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:53,210 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:53,401 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:53,558 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:53,761 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:54,894 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:57,038 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:58:57,730 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:58,066 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:58,227 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:58,424 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:58,578 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:58:58,774 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:58:59,185 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:01,325 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:02,746 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:03,086 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:03,242 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:03,439 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:03,480 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:03,596 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:03,796 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:05,619 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:07,757 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:07,762 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:08,109 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:08,258 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:08,456 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:08,620 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:08,816 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:09,890 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:12,045 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:12,781 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:13,130 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:13,284 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:13,480 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:13,635 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:13,836 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:14,186 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:16,320 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:17,801 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:18,151 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:18,284 DEBUG   SystemMonitor:7233 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-06-25 15:59:18,286 DEBUG   SenderThread:7233 [sender.py:send():378] send: telemetry
2024-06-25 15:59:18,287 DEBUG   SenderThread:7233 [sender.py:send():378] send: stats
2024-06-25 15:59:18,308 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:18,445 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:18,500 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:18,657 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:19,295 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:19,522 INFO    Thread-46 :7233 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/rajit906/Downloads/Dissertation/Symmetry-invariant-Tractable-Generative-Models/src/wandb/run-20240625_155747-96zg6qi4/files/config.yaml
2024-06-25 15:59:20,574 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:22,704 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:22,826 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:23,178 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:23,331 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:23,524 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:23,677 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:24,493 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:24,847 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:26,971 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:27,848 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:28,200 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:28,354 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:28,543 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:28,698 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:29,093 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:29,512 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:31,237 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:32,874 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:33,221 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:33,362 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:33,373 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:33,564 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:33,719 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:34,532 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:35,486 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:37,673 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:37,895 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:38,243 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:38,393 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:38,585 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:38,746 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:39,548 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:39,789 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:42,028 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:42,928 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:43,268 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:43,407 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:43,606 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:43,756 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:44,151 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:44,576 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:46,294 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:47,947 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:48,285 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:48,292 DEBUG   SenderThread:7233 [sender.py:send():378] send: stats
2024-06-25 15:59:48,427 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:48,431 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:48,630 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:48,782 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:50,301 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:50,570 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:52,707 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:52,964 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:53,304 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:53,450 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:53,648 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:53,801 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:54,843 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:55,319 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:56,978 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 15:59:57,982 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:58,323 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:58,471 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:58,670 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 15:59:58,816 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 15:59:59,112 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:00,336 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:01,245 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:03,002 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:03,335 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:03,380 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:03,484 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:03,688 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:03,832 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:05,354 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:05,520 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:07,653 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:08,023 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:08,356 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:08,501 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:08,701 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:08,851 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:09,791 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:10,372 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:11,928 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:13,038 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:13,377 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:13,520 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:13,727 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:13,869 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:14,064 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:15,393 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:16,198 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:18,052 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:18,293 DEBUG   SenderThread:7233 [sender.py:send():378] send: stats
2024-06-25 16:00:18,313 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:18,400 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:18,535 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:18,740 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:18,884 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:20,447 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:21,306 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:22,585 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:23,066 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:23,416 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:23,550 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:23,759 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:23,906 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:24,705 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:26,323 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:26,808 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:28,082 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:28,429 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:28,569 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:28,778 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:28,927 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:28,932 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:31,065 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:31,346 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:33,096 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:33,214 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:33,447 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:33,585 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:33,798 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:33,951 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:35,356 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:36,367 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:37,456 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:38,121 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:38,472 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:38,604 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:38,821 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:38,969 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:39,563 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:41,387 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:41,692 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:43,143 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:43,494 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:43,623 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:43,820 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:43,843 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:43,991 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:45,951 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:46,406 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:48,103 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:48,162 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:48,300 DEBUG   SenderThread:7233 [sender.py:send():378] send: stats
2024-06-25 16:00:48,512 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:48,644 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:48,867 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:49,013 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:50,229 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:52,315 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:52,369 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:53,182 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:53,529 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:53,659 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:53,889 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:54,029 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:00:54,482 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:56,588 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:57,328 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:58,203 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:58,551 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:58,673 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:58,698 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:00:58,913 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:00:59,051 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:00,827 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:02,353 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:02,962 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:03,222 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:03,572 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:03,690 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:03,935 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:04,073 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:05,076 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:07,205 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:07,373 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:08,246 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:08,589 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:08,710 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:08,957 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:09,091 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:09,340 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:11,435 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:12,398 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:13,264 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:13,539 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:13,614 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:13,732 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:13,973 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:14,110 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:15,670 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:17,418 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:17,763 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:18,282 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:18,300 DEBUG   SenderThread:7233 [sender.py:send():378] send: stats
2024-06-25 16:01:18,636 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:18,754 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:18,993 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:19,143 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:19,859 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:21,968 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:23,301 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:23,322 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:23,656 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:23,777 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:24,012 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:24,093 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:24,163 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:26,187 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:28,292 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:28,316 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:28,336 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:28,681 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:28,799 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:29,027 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:29,185 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:30,492 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:32,632 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:33,342 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:33,361 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:33,698 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:33,819 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:34,047 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:34,207 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
2024-06-25 16:01:34,734 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:36,860 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:38,365 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:38,380 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:38,716 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:38,838 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:38,965 ERROR   gpuapple  :7233 [gpu_apple.py:sample():110] GPU stats error: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/wandb/bin/apple_gpu_stats', '--json']' died with <Signals.SIGTRAP: 5>.
2024-06-25 16:01:39,069 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: status_report
2024-06-25 16:01:39,230 DEBUG   HandlerThread:7233 [handler.py:handle_request():158] handle_request: keepalive
